# write your docker-compose code here.Use the `docker compose` command instead of the legacy `docker-compose`, as it is integrated into Docker CLI (v20.10+),eliminating the need for a separate binary. It provides better performance, consistency, and is actively maintained, unlike the legacy command.

networks:
  todo-network:
    driver: bridge

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: tododb
      MYSQL_USER: root
      MYSQL_PASSWORD: Root@123
    ports: 
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network

  todo-application:
   image: todo-application-image:latest
   container_name: todo-application
   depends_on:
     - mysql-db
   environment:
     DB_HOST: mysql-db
     DB_USER: root
     DB_PASSWORD: Root@123
     DB_NAME: tododb
   ports:
     - "8082:8081"
   networks:
     - todo-network

volumes:
  mysql-data:

  